config/routes.rb
Rails.application.routes.draw do
  root to: 'words#index'
  resources :words

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/word.rb
class Word < ApplicationRecord
  enum :word_class, [:noun, :verb, :adjective, :adverb]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @words = Word.all
    @modify_text = modify_text(Word.where('created_at >= ?', Date.today))
  end

  def show
  end

  def new
    @word = Word.new
  end

  def create
    word = Word.new(word_params)
    word.save!
    redirect_to words_url, notice: "#{word.name}を登録しました。"
  end

  def edit
    @word = Word.find(params[:id])
  end

  def update
    @word = Word.find(params[:id])
    @word.update!(word_params)
    redirect_to words_url, notice: "#{@word.name}を更新しました。"
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy
    redirect_to words_url, notice: "#{@word.name}を削除しました。", status: :see_other
  end

  private

  def word_params
    params.require(:word).permit(:name, :word_class, :meaning)
  end

  def modify_text(words_created_at_today)
    return "なし" if words_created_at_today.empty?
      
    texts = ""
    
    words_created_at_today.each do |word|
      texts += "|"
      texts += " " + word.name + " "
      texts += "|"
      texts += " " + word.word_class_i18n +  " "
      texts += "|"
      texts +=  " " + word.meaning +  " "
      texts += "|"
      texts += "\n"
    end
    return texts
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Mydictionary
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand Mydictionary
    .container
      - if flash.notice.present?
        .alert.alert-success = flash.notice
      = yield

app/views/words/_form.html.slim
= form_with model: word, local:true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'word_name'
  .form-group
    = f.label :word_class
    = f.select :word_class, Word.word_classes_i18n.invert, include_blank: "選択してください", id: 'word_class'
  .form-group
    = f.label :meaning
    = f.text_field :meaning, class: 'form-control', id: 'word-meaning'
  = f.submit nil, class: 'btn btn-primary'

app/views/words/edit.html.slim
h1 英単語の更新

.nav.justify-content-end
  = link_to '一覧', words_path, class: 'nav-link'

=render partial: 'form', locals: { word: @word }

app/views/words/index.html.slim
h1 英単語一覧
div
  = link_to '新規登録', new_word_path, class: 'btn btn-primary'
div
  h3 ↓貼り付け用
  textarea = @modify_text


.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th = Word.human_attribute_name(:name)
      th = Word.human_attribute_name(:word_class)
      th = Word.human_attribute_name(:meaning)
      th = Word.human_attribute_name(:created_at)
  tbody
    - @words.each do |word|
      tr
        td = word.name
        td = word.word_class_i18n
        td = word.meaning
        td = word.created_at
        td
          = link_to '編集', edit_word_path(word), class: 'btn btn-primary mr-3'
          = link_to '削除', word, data: { turbo_method: :delete, turbo_confirm: "#{word.name}を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/words/new.html.slim
h1 単語の新規登録

.nav.justify-content-end
  = link_to '一覧', words_path, class: 'nav-link'

=render partial: 'form', locals: { word: @word }

app/views/words/show.html.slim
h1 Words#show
p Find me in app/views/words/show.html.slim